flower_models/urls.py
from django.urls import path

from flower_models.views import index, card, consultation, order, order_step, quiz, result, catalog, quiz_step

app_name = 'flower_models'

urlpatterns = [
    path('', index, name='index'),
    path('card/<int:bouquet_id>', card, name='card'),
    path('consultation', consultation, name='consultation'),
    path('order', order, name='order'),
    path('order_step', order_step, name='order_step'),
    path('quiz', quiz, name='quiz'),
    path('quiz-step', quiz_step, name='quiz_step'),
    path('result', result, name='result'),
    path('catalog', catalog, name='catalog')
]

flowers/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower_models.urls', namespace='flower_models')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

flower_models/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re

ORDER_CHOICES = (
    ("true", "подтверждение"),
    ("collect", "сборка"),
    ("courier", "передан курьеру"),
    ("delivered", "доставлено")
)


class Event(models.Model):
    """События"""
    title = models.CharField("Название события", max_length=200)

    def __str__(self):
        return self.title


class Bouquet(models.Model):
    """Букеты"""
    title = models.CharField("Название букета", max_length=200, unique=True)
    price = models.FloatField("Стоимость", blank=True)
    event = models.ManyToManyField(
        Event,
        verbose_name="Событие",
        related_name="events",
    )
    photo = models.ImageField("Фото")
    description = models.TextField(
        "Описание",
        blank=True
    )
    height = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='Высота(см)'
    )
    width = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='Ширина(см)'
    )

    def __str__(self):
        return self.title


class Client(models.Model):
    """Клиенты"""
    full_name = models.CharField("ФИО", max_length=200)
    phone = models.CharField('Телефон', max_length=200, unique=True)

    def clean(self):
        if self.phone:
            normalized_phone = re.sub(r'\D', '', self.phone)
            if len(normalized_phone) < 10:
                raise ValidationError("Номер телефона слишком короткий")

            self.phone = normalized_phone

    def save(self, *args, **kwargs):
        self.clean()
        super(Client, self).save(*args, **kwargs)

    def __str__(self):
        return self.full_name


class Order(models.Model):
    """Заказ"""
    client = models.ForeignKey(
        Client,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="clients"
    )
    address = models.CharField("Адрес", max_length=200)
    delivery_date = models.DateTimeField("Дата доставки")
    bouquet = models.ForeignKey(
        Bouquet,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    status = models.CharField(
        verbose_name="Статус",
        choices=ORDER_CHOICES,
        max_length=30,
        default="true",
    )

    def __str__(self):
        return self.address


class Consultation(models.Model):
    name = models.CharField("Имя", max_length=100)
    phone = models.CharField("Номер телефона", max_length=20)
    consulted = models.BooleanField("Проконсультирован", default=False)

    def __str__(self):
        return self.name

flower_models/forms.py
from django import forms
from .models import Consultation

class UserForm(forms.ModelForm):
    class Meta:
        model = Consultation
        fields = ('name', 'phone')
        labels = {
            'name': '',
            'phone': ''
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'consultation__form_input',
                                               'placeholder': "Введите Имя"}),
            'phone': forms.TextInput(attrs={'class': 'consultation__form_input',
                                            'placeholder': "+ 7 (999) 000 00 00"}),
        }

flower_models/views.py
from datetime import datetime, time

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .forms import UserForm
from .models import Bouquet, Order, Client, Consultation, Event
from django.contrib import messages



# TODO
def index(request):
    bouquets = Bouquet.objects.prefetch_related('event')
    bouquet_serialized = []
    for bouguet in bouquets:
        bouquet_serialized.append({
            'id': bouguet.id,
            'title': bouguet.title,
            'price': bouguet.price,
            "images": bouguet.photo.url,
        })

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Заявка успешно создана')
            return redirect(reverse('flower_models:index'))
        context = {'form': form, 'bouquets': bouquet_serialized}
        return render(request, 'flowers_models/index.html', context)
    context = {
        'form': UserForm(),
        'bouquets': bouquet_serialized
    }
    return render(request, 'flowers_models/index.html', context)


# TODO
def card(request, bouquet_id):
    bouquet = get_object_or_404(Bouquet, pk=bouquet_id)

    return render(
        request,
        'flowers_models/card.html',
        {
            'bouquet': bouquet
        })


# TODO
def consultation(request):
    if request.method == "POST":
        name = request.POST.get('fname')
        phone = request.POST.get('tel')
        Consultation.objects.create(name=name, phone=phone)
        messages.success(request, 'Запись на консультацию отправлена. Наш менеджер свяжется с вами в ближайшее время.')
        return redirect('index')

    return render(request, 'flowers_models/consultation.html')



# TODO
def order(request):
    context = {}
    if request.method == "POST":
         context['bouquet_title'] = request.POST['bouquet_title']
         context['bouquet_price'] = request.POST['bouquet_price']
         print(type(request.POST))
         print(context)
         return render(request, 'flowers_models/order.html', context=context)

    else:
        return redirect(reverse('flower_models:consultation'))

    print(context)
    return render(request, 'flowers_models/order.html', context=context)


# TODO
def order_step(request):
    context = {}
    status = "подтверждение"

    if request.method == "POST":
        bouquet_title = request.POST['bouquet_title']
        name = request.POST['name']
        phone = request.POST['phone']
        bouquet = Bouquet.objects.get(title=bouquet_title)
        order_time = request.POST['orderTime']
        # today = datetime.date.today()
        if order_time:
            delivery_date = datetime.now()

        try:
            # Пытаемся найти клиента по имени и телефону
            client1 = Client.objects.get(full_name=name, phone=phone)
        except Client.DoesNotExist:
            # Если клиент не найден, создаем нового
            client1 = Client.objects.create(full_name=name, phone=phone)

        # Дальнейшие действия с client1 (например, создание заказа)
        order = Order.objects.create(
            client=client1,
            delivery_date=delivery_date,
            status=status,
            address=request.POST['address'],
            bouquet=bouquet
        )

        return render(request, 'flowers_models/order-step.html') #context=context)

    return render(request, 'flowers_models/order-step.html')


# TODO
def quiz(request):
    if request.method == 'POST':
        event_name = request.POST.get('event')
        print(event_name)
        context = {
            'event': event_name
        }
        return render(request, 'flowers_models/quiz-step.html', context)

    return render(request, 'flowers_models/quiz.html')

def quiz_step(request):
    if request.method == 'POST':
        event = request.POST.get('event')
        price_range = request.POST.get('el_price')
        bouquets = Bouquet.objects.filter(event__title=event)

        if price_range:
            if price_range == "До 1000":
                bouquets = bouquets.filter(price__lte=1000)
            elif price_range == "До 5000":
                bouquets = bouquets.filter(price__gt=1000, price__lte=5000)
            elif price_range == "От 5000":
                bouquets = bouquets.filter(price__gt=5000)
            context = {
                'bouquets': bouquets,
            }
            if bouquets.exists():
                return render(request, 'flowers_models/result.html', context)
            else:
                return render(request, 'flowers_models/quiz.html')

    return render(request, 'flowers_models/quiz.html')


# TODO
def result(request):
    if request.method == 'POST':
        pass
    return render(request, 'flowers_models/result.html')


# TODO
def catalog(request):
    bouquets = Bouquet.objects.prefetch_related('event')
    bouquet_serialized = []
    for bouguet in bouquets:
        bouquet_serialized.append({
            'id': bouguet.id,
            'title': bouguet.title,
            'price': bouguet.price,
            "images": bouguet.photo.url,
        })
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Заявка успешно создана')
            return redirect(reverse('flower_models:index'))
        context = {'form': form, 'bouquets': bouquet_serialized}
        return render(request, 'flowers_models/index.html', context)
    context = {
        'form': UserForm(),
        'bouquets': bouquet_serialized
    }
    return render(request, 'flowers_models/catalog.html', context)

flower_models/templates/flowers_models/card.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section id="card">
        <div class="container">
            <div class="card ficb">
                <div class="card__block card__block_first">
                    <img src="{{ bouquet.photo.url }}" alt="img" class="card__img">
                </div>
                <div class="card__block card__block_sec">
                    <div class="title">{{ bouquet.title }}</div>
                    <div class="card__block_price">{{ bouquet.price }}</div>
                    <div class="card__elems ">
                        <span class="card__elems_intro">Описание</span>
                        <div class="card__items">
							{{ bouquet.description|linebreaksbr }}
                        </div>
                    </div>
                    <div class="card__elems ">
                        <span class="card__elems_intro">Размер</span>
                        <div class="card__items">
							<span class="card_items_intro">
								Высота - {{ bouquet.height }}см.
							</span>
                            <span class="card_items_intro">
								Ширина - {{ bouquet.width }}см.
							</span>
                        </div>
                    </div>
                    <form action="/order" method="post">
						{% csrf_token %}
						<input name="bouquet_price" value="{{ bouquet.price }}" type="hidden">
						<input name="bouquet_title" value="{{ bouquet.title }}" type="hidden">
						<button class="btn largeBtn card__btn">Заказать букет</button>
					</form>
                </div>
            </div>
        </div>
    </section>
    <section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                <form action="#" class="consultation__form">
                    <input type="text" name="fname" class="consultation__form_input" placeholder="Введите Имя" required>
                    <input type="text" name="tel" class="consultation__form_input" placeholder="+ 7 (999) 000 00 00"
                           required>
                    <button type="submit" class="consultation__form_btn">Отправить</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

flower_models/templates/flowers_models/catalog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="catalog">
        <div class="container p100">
            <div class="catalog">
                <div class="title">Все букеты</div>
                {% for bouquet in bouquets %}
                    <div class="catalog__item">
                        <a href="{% url 'flower_models:card' bouquet.id %}">
                            <div class="catalog__image" style="background-image: url('{{ bouquet.images }}')"></div>
                        </a>
                        <div class="catalog__details">
                            <h3 class="catalog__name">Название {{ bouquet.title }}</h3>
                            <p class="catalog__price">Стоимость {{ bouquet.price }}</p>
                        </div>

                    </div>
                {% endfor %}
            </div>
            <!--            <button class="btn largeBtn catalog__btn">Показать ещё</button>-->

        </div>
        <section id="consultation">
            <div class="container">
                <div class="consultation">
                    <div class="title consultation__title">Оставьте заявку на консультацию</div>
                    <form action="#" class="consultation__form" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="consultation__form_btn">Отправить</button>
                    </form>
                </div>
            </div>
        </section>
{% endblock %}

flower_models/templates/flowers_models/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="mainBg">
        <section id="banner">
            <div class="container">
                <div class="banner">
                    <div class="banner__block">
                        <h1 class="banner__title">Мастерская цветов</h1>
                        <p class="banner__text">Подберем для вас букет за два шага, который идеально подойдет под вашу
                            ситуацию</p>
                        <a href="{% url 'flower_models:quiz' %}" >
                            <button class="btn banner__btn">Подобрать букет</button>
                        </a>
                    </div>
                    <img src="{% static 'img/bannerImg.png' %}" alt="banner Img" class="banner__img">
                </div>
            </div>
        </section>
    </div>
    <section id="recommended">
        <div class="container">
            <div class="recommended p100">
                <div class="title">Рекомендуем</div>

                <div class="recommended__elems ficb">
                    {% for bouquet in bouquets|slice:"0:3" %}

                    <div class="recommended__block recommended__block_first">

                        <div class="recommended__block_elems ficb">
                            <span class="recommended__block_intro"> Название: {{bouquet.title}}</span>
                            <span class="recommended__block_price">Цена: {{bouquet.price}}</span>
                        </div>
                        <div class="catalog__image" style="background-image: url('{{ bouquet.images }}')">
                            <a href="{% url 'flower_models:card' bouquet.id %}">
<!--                           <img src="{{bouquet.images}}" />-->

                        </div>

                    </div>

                    {% endfor %}

<!--                    <div class="recommended__block recommended__block_first">-->
<!--                        <div class="recommended__block_elems ficb">-->
<!--                            <span class="recommended__block_intro">Летнее утро</span>-->
<!--                            <span class="recommended__block_price">3 600 руб</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="recommended__block recommended__block_sec">-->
<!--                        <div class="recommended__block_elems ficb">-->
<!--                            <span class="recommended__block_intro">Зимняя сказка</span>-->
<!--                            <span class="recommended__block_price">4 100 руб</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="recommended__block recommended__block_thr">-->
<!--                        <div class="recommended__block_elems ficb">-->
<!--                            <span class="recommended__block_intro">Нежный</span>-->
<!--                            <span class="recommended__block_price">2 900 руб</span>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
                <a href="{% url 'flower_models:catalog' %}">
                    <button class="btn recommended__btn">Показать всю коллекцию</button>
                </a>
            </div>
        </div>
    </section>
    <section id="contacts">
        <div class="container">
            <div class="contacts">
                <div class="title">Как нас найти</div>
                <div class="contacts__elems ficb">
                    <div class="contacts__block">
                        <div class="contacts__block_item ficc">
                            <div class="contacts__block_intro">ул. Пушкинская, 69</div>
                            <a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
                        </div>
                        <div class="contacts__block_item ficc">
                            <div class="contacts__block_intro">ул. Жукова, 13</div>
                            <a href="tel:89112855571" class="contacts__block_tel">8 (911) 28 55 571</a>
                        </div>
                        <div class="contacts__block_item ficc">
                            <div class="contacts__block_intro">ул. Красная, 384</div>
                            <a href="tel:89113966682" class="contacts__block_tel">8 (911) 39 66 682</a>
                        </div>
                    </div>
                    <img src="{% static 'img/contactsImg.jpg' %}" alt="contactsImg" class="contacts__img">
                    <div class="contacts__map">
                        <script type="text/javascript" charset="utf-8" async
                                src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af39d7a7f1829359b6ffe21ab6356fcaeace17d528d6522dba8772f885c8b1a7d&amp;width=398&amp;height=316&amp;lang=ru_RU&amp;scroll=true"></script>
                    </div>
                </div>
                <a href="{% url 'flower_models:order' %}" >
                    <button class="btn contacts__btn">Заказать доставку</button>
                </a>
            </div>
        </div>
    </section>
    <section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                <form action="#" class="consultation__form" method="POST">
                    {% csrf_token %}
						{{form}}
<!--                    <input type="text" name="fname" class="consultation__form_input" placeholder="Введите Имя" required>-->
<!--                    <input type="text" name="tel" class="consultation__form_input" placeholder="+ 7 (999) 000 00 00"-->
<!--                           required>-->
                    <button type="submit" class="consultation__form_btn">Отправить</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

flower_models/templates/flowers_models/quiz-step.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="quiz">
        <div class="container">
            <div class="quiz">
                <div class="quiz__back ">
                    <a href="#" class="quiz__back_link fic"><img src="{% static 'img/arrow-left.svg' %}"
                                                                 alt="arrow-left"
                                                                 class="arrowLeft">
                        <span class="quiz__back_intro">Назад</span></a>
                </div>
                <div class="quiz__block">
                    <h1 class="quiz__title">На какой бюджет рассчитываете?</h1>
                     <form method="post" action="{% url 'flower_models:quiz_step' %}">
                        {% csrf_token %}
                         <div class="quiz__elems fic">
                            <button type="submit" name="el_price" value="До 1000" class="quiz__elem">До 1 000 руб</button>
                            <button type="submit" name="el_price" value="До 5000" class="quiz__elem">1 000 - 5 000 руб</button>
                            <button type="submit" name="el_price" value="От 5000" class="quiz__elem">от 5 000 руб</button>
                            <button type="submit" name="el_price" value="От 10000" class="quiz__elem">Не имеет значения</button>
                             <input type="hidden" name="event" value="{{ event }}">

<!--                    <div class="quiz__elems fic">-->
<!--                        <button class="quiz__elem">До 1 000 руб</button>-->
<!--                        <button class="quiz__elem">1 000 - 5 000 руб</button>-->
<!--                        <button class="quiz__elem">от 5 000 руб</button>-->
<!--                        <button class="quiz__elem">Не имеет значения</button>-->
<!--                    </div>-->

                         </div>
                     </form>


                    <div class="quiz__progress">
                        <div class="quiz__progress_step">
                            <span class="quiz__progress_num">2</span>
                            <span class="quiz__progress_in"> шаг из </span>
                            <span class="quiz__progress_num">2</span>
                        </div>
                        <div class="quiz__progress_line">
                            <div class="quiz__progress_lineActive"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

flower_models/templates/flowers_models/quiz.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="quiz">
        <div class="container">
            <div class="quiz">
                <div class="quiz__back ">
                    <a href="#" class="quiz__back_link fic"><img src="{% static 'img/arrow-left.svg' %}"
                                                                 alt="arrow-left"
                                                                 class="arrowLeft">
                        <span class="quiz__back_intro">Назад</span></a>
                </div>
                <div class="quiz__block">
                    <h1 class="quiz__title">К какому событию нужен букет?</h1>
                    <form method="post" action="{% url 'flower_models:quiz' %}">
                        {% csrf_token %}
                    <div class="quiz__elems fic">
                        <button type="submit" name="event" value="Свадьба" class="quiz__elem">Свадьба</button>
                        <button type="submit" name="event" value="День рождения" class="quiz__elem">День рождения</button>
                        <button type="submit" name="event" value="Без повода" class="quiz__elem">Без повода</button>


<!--                        <button class="quiz__elem">Свадьба</button>-->
<!--                        <button class="quiz__elem">День рождения</button>-->
<!--                        <button class="quiz__elem">Без повода</button>-->
                    </div>
                        </form>
                    <div class="quiz__progress">
                        <div class="quiz__progress_step">
                            <span class="quiz__progress_num">1</span>
                            <span class="quiz__progress_in"> шаг из </span>
                            <span class="quiz__progress_num">2</span>
                        </div>
                        <div class="quiz__progress_line">
                            <div class="quiz__progress_lineActive"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

flower_models/templates/flowers_models/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="result">
        <div class="container">
            <div class="result p100">
                <div class="title">Мы подобрали специально для Вас</div>
                <div class="result__block ficb">

                    {% for bouquet in bouquets|slice:"0:1" %}
                    <div class="result__elems">
                        <div class="card__elems ">
                            <span class="card__elems_intro">Описание:</span>
                            <div class="card__items">
                                <p class="card__items_text card__items_text__first">
                                    {{bouquet.description}}
                                </p>
<!--                                <p class="card__items_text">-->
<!--                                    Букеты из полевых цветов - это не только прекрасный подарок, но и отличный способ-->
<!--                                    выразить свои чувства.-->
<!--                                </p>-->
                            </div>
                        </div>
                        <div class="card__elems ">
                            <span class="card__elems_intro">Состав:</span>
                            <div class="card__items">
                                <p class="card__items_text card__items_text__first">
                                    Альстромерия белая 1 шт., Эустома белая 1 шт, Ромашка 1 шт, Роза пионовидная 1 шт
                                </p>

                            </div>
                        </div>
                    </div>
                    <img src="{% static 'img/cardImg.jpg' %}" alt="result Img" class="result__block_img">
                    <div class="result__items">
                        <div class="title result__items_title">title - {{bouquet.title}}</div>
                        <div class="result__items_price">{{bouquet.price}} руб</div>
                        <form action="/order" method="post">
						{% csrf_token %}
						<input name="bouquet_price" value="{{ bouquet.price }}" type="hidden">
						<input name="bouquet_title" value="{{ bouquet.title }}" type="hidden">
						<button class="btn largeBtn card__btn">Заказать букет</button>
					    </form>
<!--                        <button class="btn result__items_btn">Заказать букет</button>-->
                        <hr class="result__items_line"/>
                        <div class="result__items_intro">Хотите что-то более специальное?</div>
                        <div class="result__items_block">
                            <a href="{% url 'flower_models:catalog' %}">
                            <button class="btn largeBtn result__items_block__btn">Смотреть всю коллекцию</button>
                            </a>
                            <a href="{% url 'flower_models:consultation' %}">
                            <button class="btn largeBtn result__items_block__btn">Заказать консультацию</button>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <section id="contacts">
        <div class="container">
            <div class="contacts">
                <div class="title">Как нас найти</div>
                <div class="contacts__elems ficb">
                    <div class="contacts__block">
                        <div class="contacts__block_item ficc">
                            <div class="contacts__block_intro">ул. Пушкинская, 69</div>
                            <a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
                        </div>
                        <div class="contacts__block_item ficc">
                            <div class="contacts__block_intro">ул. Пушкинская, 69</div>
                            <a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
                        </div>
                        <div class="contacts__block_item ficc">
                            <div class="contacts__block_intro">ул. Пушкинская, 69</div>
                            <a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
                        </div>
                    </div>
                    <img src="{% static 'img/contactsImg.jpg' %}" alt="contactsImg" class="contacts__img">
                    <div class="contacts__map">
                        <script type="text/javascript" charset="utf-8" async
                                src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af39d7a7f1829359b6ffe21ab6356fcaeace17d528d6522dba8772f885c8b1a7d&amp;width=398&amp;height=316&amp;lang=ru_RU&amp;scroll=true"></script>
                    </div>
                </div>
                <button class="btn contacts__btn">Заказать доставку</button>
            </div>
        </div>
    </section>
    <section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                <form action="#" class="consultation__form">
                    <input type="text" name="fname" class="consultation__form_input" placeholder="Введите Имя" required>
                    <input type="text" name="tel" class="consultation__form_input" placeholder="+ 7 (999) 000 00 00"
                           required>
                    <button type="submit" class="consultation__form_btn">Отправить</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}